//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XonickPay.Api.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful!.
        /// </summary>
        public static string E_HRMS_0001 {
            get {
                return ResourceManager.GetString("E_HRMS_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully retrieved all user data..
        /// </summary>
        public static string E_HRMS_0002 {
            get {
                return ResourceManager.GetString("E_HRMS_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digilocker link generated successfully..
        /// </summary>
        public static string E_HRMS_0003 {
            get {
                return ResourceManager.GetString("E_HRMS_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhaar details updated successfully..
        /// </summary>
        public static string E_HRMS_0004 {
            get {
                return ResourceManager.GetString("E_HRMS_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhaar Phone number and Digilocker Id updated successfully..
        /// </summary>
        public static string E_HRMS_0005 {
            get {
                return ResourceManager.GetString("E_HRMS_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan verification successful!.
        /// </summary>
        public static string E_HRMS_0006 {
            get {
                return ResourceManager.GetString("E_HRMS_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video uploaded successfully..
        /// </summary>
        public static string E_HRMS_0007 {
            get {
                return ResourceManager.GetString("E_HRMS_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank verification successful!.
        /// </summary>
        public static string E_HRMS_0008 {
            get {
                return ResourceManager.GetString("E_HRMS_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information data fetched successfully..
        /// </summary>
        public static string E_HRMS_0009 {
            get {
                return ResourceManager.GetString("E_HRMS_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhaar number and Phone number updated successfully..
        /// </summary>
        public static string E_HRMS_0010 {
            get {
                return ResourceManager.GetString("E_HRMS_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhaar number verified successfully!.
        /// </summary>
        public static string E_HRMS_0011 {
            get {
                return ResourceManager.GetString("E_HRMS_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP sent successfully..
        /// </summary>
        public static string E_HRMS_0012 {
            get {
                return ResourceManager.GetString("E_HRMS_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number verified successfully..
        /// </summary>
        public static string E_HRMS_0013 {
            get {
                return ResourceManager.GetString("E_HRMS_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All banks fetched successfully..
        /// </summary>
        public static string E_HRMS_0014 {
            get {
                return ResourceManager.GetString("E_HRMS_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet created successfully!.
        /// </summary>
        public static string E_HRMS_0015 {
            get {
                return ResourceManager.GetString("E_HRMS_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fetched successfully!.
        /// </summary>
        public static string E_HRMS_0016 {
            get {
                return ResourceManager.GetString("E_HRMS_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fetched successfully by Id..
        /// </summary>
        public static string E_HRMS_0017 {
            get {
                return ResourceManager.GetString("E_HRMS_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving all Price Type records..
        /// </summary>
        public static string E_HRMS_0018 {
            get {
                return ResourceManager.GetString("E_HRMS_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Price Type by Id..
        /// </summary>
        public static string E_HRMS_0019 {
            get {
                return ResourceManager.GetString("E_HRMS_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving all Currency records..
        /// </summary>
        public static string E_HRMS_0020 {
            get {
                return ResourceManager.GetString("E_HRMS_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Currency by Id..
        /// </summary>
        public static string E_HRMS_0021 {
            get {
                return ResourceManager.GetString("E_HRMS_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement: Step 1 creation successful.
        /// </summary>
        public static string E_HRMS_0022 {
            get {
                return ResourceManager.GetString("E_HRMS_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement: Step 2 creation successful.
        /// </summary>
        public static string E_HRMS_0023 {
            get {
                return ResourceManager.GetString("E_HRMS_0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement: Step 3 creation successful.
        /// </summary>
        public static string E_HRMS_0024 {
            get {
                return ResourceManager.GetString("E_HRMS_0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched all Advertisement records.
        /// </summary>
        public static string E_HRMS_0025 {
            get {
                return ResourceManager.GetString("E_HRMS_0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched advertisements by Id .
        /// </summary>
        public static string E_HRMS_0026 {
            get {
                return ResourceManager.GetString("E_HRMS_0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully..
        /// </summary>
        public static string E_HRMS_0027 {
            get {
                return ResourceManager.GetString("E_HRMS_0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data added successfully.
        /// </summary>
        public static string E_HRMS_0028 {
            get {
                return ResourceManager.GetString("E_HRMS_0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Removed Suceessfully.
        /// </summary>
        public static string E_HRMS_0029 {
            get {
                return ResourceManager.GetString("E_HRMS_0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face matched with .
        /// </summary>
        public static string E_HRMS_0030 {
            get {
                return ResourceManager.GetString("E_HRMS_0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF load successfully.
        /// </summary>
        public static string E_HRMS_0031 {
            get {
                return ResourceManager.GetString("E_HRMS_0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User approve successfully.
        /// </summary>
        public static string E_HRMS_0032 {
            get {
                return ResourceManager.GetString("E_HRMS_0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        public static string E_HRMS_0033 {
            get {
                return ResourceManager.GetString("E_HRMS_0033", resourceCulture);
            }
        }
    }
}
