<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\**" />
    <EmbeddedResource Remove="Common\**" />
    <None Remove="Common\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Filters\lead-filters.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharedService\Shared.Models\Shared.Models.csproj" />
    <ProjectReference Include="..\Lead.Domain\Lead.Domain.csproj" />
  </ItemGroup>

</Project>
